(function(z){
var nK=function(a,b,c){z.fm.call(this,a,1,0,b,c)};var oK=function(a){return(0,z.Q)((a.ra?'\x3cdiv class\x3d"fyre-featured-content-wrapper"\x3e':"")+(0,z.Q)('\x3cheader class\x3d"fyre-featured-header"\x3e\x3cspan class\x3d"fyre-featured-header-icon"\x3e\x3c/span\x3e'+(0,z.Q)('\x3cspan class\x3d"fyre-featured-title"\x3e'+z.P(a.j.jY)+"\x3c/span\x3e")+"\x3c/header\x3e")+(0,z.Q)('\x3cdiv class\x3d"fyre-featured-body"\x3e\x3c/div\x3e')+(a.ra?"\x3c/div\x3e":""))};
var pK=function(a){var b=z.Q,c='\x3cheader class\x3d"fyre-comment-head"\x3e\x3c/header\x3e\x3csection class\x3d"fyre-comment-body"\x3e'+(0,z.Q)('\x3cspan class\x3d"fyre-featured-quote"\x3e\x3c/span\x3e\x3cdiv class\x3d"fyre-comment"\x3e\x3c/div\x3e')+"\x3c/section\x3e",d;d=z.Q;var f='\x3cfooter class\x3d"fyre-comment-footer"\x3e\x3cspan class\x3d"fyre-featured-author"\x3e\x3cspan class\x3d"fyre-featured-authored-by"\x3eBy \x3c/span\x3e'+(0,z.Q)((a.t.Rb&&!a.t.Aa?'\x3cspan class\x3d"fyre-comment-username"\x3e\x3cstrong\x3e'+
z.P(a.t.aa)+"\x3c/strong\x3e\x3c/span\x3e":'\x3ca class\x3d"fyre-comment-username"'+(a.t.Aa?'href\x3d"'+z.R(z.S(a.t.Aa))+'" target\x3d"_blank"':"")+"\x3e"+z.P(a.t.aa)+"\x3c/a\x3e")+" ")+z.Ho(z.Y.SJ(a))+z.Ho(z.ip(a))+z.Ho(z.kp(a))+(0,z.Q)('\x3cspan class\x3d"fyre-circle-separator"\x3e\x3c/span\x3e');a=(0,z.Q)(a.t.ic?'\x3ca href\x3d"https://twitter.com" class\x3d"fyre-social-provider" target\x3d"_blank"\x3e\x3ctime class\x3d"fyre-comment-date"\x3e'+z.P(a.bl)+"\x3c/time\x3e\x3c/a\x3e":'\x3ci class\x3d"fyre-social-provider"\x3e\x3c/i\x3e\x3ctime class\x3d"fyre-comment-date"\x3e'+
z.P(a.bl)+"\x3c/time\x3e");d=d(f+a+'\x3c/span\x3e\x3cspan class\x3d"fyre-comment-like"\x3e\x3c/span\x3e\x3c/footer\x3e');return b(c+d+'\x3cdiv class\x3d"fyre-comment-divider"\x3e\x3c/div\x3e')};var qK=function(a){return(0,z.Q)('\x3ca class\x3d"fyre-comment-removal fyre-comment-action-button" title\x3d"'+z.R(a.vE)+'"\x3e'+z.P(a.vE)+"\x3c/a\x3e")};var rK=function(a){z.T.call(this);this.n=a};var sK=function(a){z.F.eb()||z.qn(a.n,z.F)?z.N(a.c,!0):z.N(a.c,!1)};
var tK=function(a){var b=z.W.g;if(z.qn(a.n,z.F))return z.W.get(b.yh);if(z.F.eb())return z.W.get(b.Lp)};var uK=function(a,b){var c={};c[z.zu]=!0;z.yu.call(this,a,b,c);this.ea=z.tv;this.wm=pK;this.Ua=new z.Kw(this.n);this.D(this.Ua);this.uI=new rK(this.n);this.D(this.uI);this.Ze=new z.Pw({ya:this.n,Ra:!0,pU:!0,vs:z.Zm,uq:this.d.u.gb()});this.D(this.Ze)};var vK=function(a){var b=!a.mz();z.N(a.Ua.f(),b)};z.wK=function(a,b){z.T.call(this,b);this.d=a;this.WU=2;this.content=new z.wf};
var xK=function(a,b){var c=new uK(a.d,b);a.D(c,!0)};var yK=function(a,b){for(var c,d=0,f=a.Nc();d<f;d++)if(a.rd(d).n.id===b){c=a.rd(d);break}c&&(d=(0,z.s)(function(){this.content.remove(b);this.Nc()||(z.Oc(this.c),this.q())},a),zK(a,c,d))};var zK=function(a,b,c){var d=new nK(b.f(),200),f=(0,z.s)(a.removeChild,a,b,!0);d.vd=function(){nK.prototype.vd.call(d);f();c()};d.play()};z.az.prototype.Mr=z.L(60,function(a){z.pn(this.n)?(a.preventDefault(),z.Yw(this)):z.az.b.Mr.call(this,a)});z.v(nK,z.fm);z.v(rK,z.T);z.e=rK.prototype;z.e.r=function(){var a=this.s();this.c=z.vo(qK,a);sK(this)};z.e.m=function(){z.F.on(z.F.Ca.Wf,this.fo,this);this.p().e(this.c,"click",this.pc)};z.e.fo=function(){this.c&&!this.La&&(this.c.innerHTML=tK(this),sK(this))};z.e.s=function(){return{vE:tK(this)}};z.e.pc=function(){var a;z.qn(this.n,z.F)?a="delete":z.F.eb()&&(a="feature");this.dispatchEvent({type:"action_clicked",key:a,n:this.n,t:this.n.get(this.n.k.wc)})};z.e.R=function(){z.F.off(null,null,this);rK.b.R.call(this)};z.v(uK,z.yu);z.e=uK.prototype;z.e.qO=function(a){a.preventDefault();var b=z.Od;a=this.t.Rb();b=this.t.get(b.ac);a&&!b||this.dispatchEvent({type:"author_click",t:this.t})};z.e.K=function(a){uK.b.K.call(this,a);a=this.o("fyre-comment-like");this.Ze.S(a);this.Ua.ra(this.Gn);this.uI.ra(this.Gn)};
z.e.m=function(){uK.b.m.call(this);this.jz(z.w.FX&&this.t&&!this.t.get(this.t.k.oB));vK(this);var a=this.p();a.e(this.Ua,"replyCommentClicked",this.Mr);a.e(this.o("fyre-comment-date"),"click",this.HR);var b=this.o("fyre-comment-username");a.e(b,"click",this.qO)};z.e.nq=z.n;z.e.Oq=z.n;z.e.KJ=z.n;z.e.ci=function(){vK(this)};z.e.cx=function(){vK(this)};z.e.Mr=function(){this.dispatchEvent({type:"request_content_reply",Zk:this.n.id})};
z.e.HR=function(){this.dispatchEvent({type:"request_content_context",Zk:this.n.id})};z.e.h=function(){uK.b.h.call(this)};z.v(z.wK,z.T);z.e=z.wK.prototype;z.e.eh=function(){this.dispatchEvent({type:"request_featured_content",PY:this})};z.e.K=function(a){var b=this.s();z.so(a,oK,b);z.wK.b.K.call(this,a);this.pD=this.o("fyre-featured-body")};z.e.m=function(){z.wK.b.m.call(this);this.p().e(this,"action_clicked",this.kR)};z.e.s=function(){return{j:this.rw()}};z.e.rw=function(){return{jY:z.W.get(z.W.g.iL)}};z.e.Vw=function(a){this.content.get(a.id)?this.aA(a):a.get(z.Lm)===z.Et.Kp&&a.get(z.an).featuredmessage&&this.content.add(a)};
z.e.zF=function(){z.hj(this.content.ib,function(a,b){return a.get(z.an).featuredmessage.value-b.get(z.an).featuredmessage.value});var a,b,c;for(c=0;this.Nc()<this.WU&&c<this.content.length;c++)a=this.content.ib[this.content.length-1-c],b=a.get(a.k.wc),b.zx()||xK(this,a);this.Nc()?z.N(this.f(),!0):(z.Oc(this.c),this.q())};z.e.Ea=function(){return this.pD};z.e.kR=function(a){yK(this,a.n.id)};z.e.Zw=function(a){var b=this.content.get(a.jk);b&&z.tn(b,a)};
z.e.JF=function(a,b){var c=this.content.get(b);c&&(z.sn(c,a)||yK(this,b))};z.e.aA=function(a){a.get(z.Lm)!==z.Et.Kp&&yK(this,a.id)};z.e.h=function(){this.pD=this.content=this.d=null;z.wK.b.h.call(this)};})(fyre.conv);
